trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'package'
    
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: asem4devsotf002'
  inputs:
    azureSubscription: 'Specsavers IT - EMEA - SOCUK - DEV'
    WebAppKind: webAppLinux
    WebAppName: asem4devsotf002
    Package: $(System.DefaultWorkingDirectory)/target/app.jar