server:
  port: 8080
  compression:    enabled: true
    min-response-size: 2KB
    mime-types:    - text/html
    - text/xml
    - text/plain
    - text/css
    - text/javascript
    - application/javascript
    - application/json

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

graphiql:  cdn:    enabled: true
