server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types:
    - text/html
    - text/xml
    - text/plain
    - text/css
    - text/javascript
    - application/javascript
    - application/json

spring:
  datasource:
    url: jdbc:mysql://dbaasem4sotf001.mysql.database.azure.com:3306/soa8306?useSSL=true&requireSSL=false
    username: bjssadmin@dbaasem4sotf001
    password: 7VQmzJe@6r25
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true


graphql:
  extended-scalars: DateTime, Date
  servlet:
    max-query-depth: 20
    cors:
      allowed-origins: "*"
      allowed-methods: GET, HEAD, POST, OPTIONS
    

