server:
  port: 8080

spring:
  profiles:
    group:
      default:
        - "common"
        - "commonDbLegacyAsMainProd"
      dev:
        - "common"
        - "commonDev"
        - "commonDbLegacyAsMainDev"
  datasource:
    url: jdbc:mysql://${DATABASE_SERVER}/soa8306?useSSL=true&requireSSL=false
