region: common

server:
  port: 8200

spring:
  profiles:
    group:
      default:
        - "common"
        - "commonLiquibase"
        - "commonDbLegacyProd"
        - "service"
      dev:
        - "common"
        - "commonLiquibase"
        - "commonDbLegacyDev"
        - "commonDev"
        - "service"
        - "serviceDev"
  datasource:
    url: jdbc:sqlserver://${DATABASE_SERVER};databaseName=clinical_microservice
  jpa:
    properties:
      hibernate:
        integrator_provider: com.specsavers.socrates.clinical.tools.ClassImportIntegratorProvider

logging:
  level:
    com.specsavers.socrates.clinical: INFO
