---
trigger: none
pr: none

resources:
  pipelines:
  - pipeline: java-clinical_microservice-build
    source: java-clinical_microservice-build
    trigger:
      enabled: true
      branches:
        include:
          - main

variables:
- template: ../vars/common.yml

stages:
- stage: DeployDev
  displayName: Deploy Dev Stage
  jobs:
  - deployment: Development
    displayName: Deploy Clinical API
    variables:
    - template: ../vars/development.yml
    pool:
      vmImage: ${{ variables.vmImage }}
    environment: ${{ variables.adoEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deployment-steps.yml
            parameters:
              artifactFeed: ${{ variables.artifactFeed }}
              azureSubscription: ${{ variables.azureSubscription }}
              buildArtifactName: ${{ variables.buildArtifactName }}
              buildMetadataName: ${{ variables.buildMetadataName }}
              ciPipeline: ${{ variables.ciPipeline }}
              projectName: ${{ variables.projectName }}
              appServiceName: ${{ variables.appServiceName }}