---
parameters:
- name: artifactFeed
  type: string
- name: azureSubscription
  type: string
- name: buildArtifactName
  type: string
- name: buildMetadataName
  type: string
- name: ciPipeline
  type: string
- name: projectName
  type: string
- name: appServiceName
  type: string

steps:
- checkout: none
- task: DownloadPipelineArtifact@2
  displayName: Download Build Metadata
  inputs:
    source: specific
    project: $(System.TeamProject)
    pipeline: ${{ parameters.ciPipeline }}
    runVersion: latestFromBranch
    runBranch: $(Build.SourceBranch)
    artifact: ${{ parameters.buildMetadataName }}
    path: $(Pipeline.Workspace)/${{ parameters.ciPipeline }}/${{ parameters.buildMetadataName }}
- script: |
    VERSION=$(jq .version $(Pipeline.Workspace)/${{ parameters.ciPipeline }}/${{ parameters.buildMetadataName }}/metadata.json -r)
    echo "##vso[task.setvariable variable=version]$VERSION"
    echo $VERSION
  displayName: Get Version Info
- task: DownloadPackage@1
  displayName: Download Maven Package
  inputs:
    packageType: maven
    feed: ${{ parameters.artifactFeed }}
    definition: 'com.specsavers.socrates:${{ parameters.buildArtifactName }}'
    version: $(version)
    files: 'app.jar'
    downloadPath: $(Pipeline.Workspace)/${{ parameters.ciPipeline }}/${{ parameters.buildArtifactName }}
- script: |
    ls -la $(Pipeline.Workspace)
    ls -la $(Pipeline.Workspace)/${{ parameters.ciPipeline }}
    ls -la $(Pipeline.Workspace)/${{ parameters.ciPipeline }}/${{ parameters.buildArtifactName }}
    ls -la $(Pipeline.Workspace)/${{ parameters.ciPipeline }}/${{ parameters.buildMetadataName }}
  displayName: Show Content
- task: AzureRMWebAppDeployment@4
  displayName: Azure App Service Deploy
  inputs:
    connectionType: AzureRM
    connectedServiceName: ${{ parameters.azureSubscription }}
    webAppKind: webAppLinux
    webAppName: ${{ parameters.appServiceName }}
    package: $(Pipeline.Workspace)/${{ parameters.ciPipeline }}/${{ parameters.buildArtifactName }}/*.jar
    startupCommand: 'java -jar /home/site/wwwroot/${{ parameters.buildArtifactName }}-$(version).jar'